In [1]:
import pandas as pd

In [2]:
movies = pd.read_csv('data.csv')

In [3]:
movies.head(10)

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,23-09-1994,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,19-10-1995,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,14-03-1972,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,15-12-1993,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,20-12-1974,8.6,9811
5,667257,Impossible Things,"Family,Drama",es,"Matilde is a woman who, after the death of her...",14.358,17-06-2021,8.6,255
6,129,Spirited Away,"Animation,Family,Fantasy",ja,"A young girl, Chihiro, becomes trapped in a st...",92.056,20-07-2001,8.5,13093
7,730154,Your Eyes Tell,"Romance,Drama",ja,"A tragic accident lead to Kaori's blindness, b...",51.345,23-10-2020,8.5,339
8,372754,Dou kyu sei – Classmates,"Romance,Animation",ja,"Rihito Sajo, an honor student with a perfect s...",14.285,20-02-2016,8.5,239
9,372058,Your Name.,"Romance,Animation,Drama",ja,High schoolers Mitsuha and Taki are complete s...,158.270,26-08-2016,8.5,8895

In [4]:
movies.describe()

                  id    popularity  vote_average    vote_count
count   10000.000000  10000.000000  10000.000000  10000.000000
mean   161243.505000     34.697267      6.621150   1547.309400
std    211422.046043    211.684175      0.766231   2648.295789
min         5.000000      0.600000      4.600000    200.000000
25%     10127.750000      9.154750      6.100000    315.000000
50%     30002.500000     13.637500      6.600000    583.500000
75%    310133.500000     25.651250      7.200000   1460.000000
max    934761.000000  10436.917000      8.700000  31917.000000

In [5]:
movies.isnull().sum()

id                    0
title                 0
genre                 3
original_language     0
overview             13
popularity            0
release_date          0
vote_average          0
vote_count            0
dtype: int64

In [6]:
movies.columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count'],
      dtype='object')

In [7]:
movies=movies[['id', 'title', 'overview', 'genre']]

In [8]:
movies

,id,title,overview,genre
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,"Drama,Crime"
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","Comedy,Drama,Romance"
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama,Crime"
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"Drama,History,War"
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...,"Drama,Crime"
...,...,...,...,...
9995,10196,The Last Airbender,"The story follows the adventures of Aang, a yo...","Action,Adventure,Fantasy"
9996,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...,"Action,TV Movie,Science Fiction,Comedy,Adventure"
9997,13995,Captain America,"During World War II, a brave, patriotic Americ...","Action,Science Fiction,War"
9998,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...,"Adventure,Fantasy,Action,Drama"
9999,455957,Domino,Seeking justice for his partner’s murder by an...,"Thriller,Action,Crime"

In [9]:
movies['tags'] = movies['overview']+movies['genre']

In [10]:
movies

,id,title,overview,genre,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,"Drama,Crime",Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","Comedy,Drama,Romance","Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama,Crime","Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"Drama,History,War",The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...,"Drama,Crime",In the continuing saga of the Corleone crime f...
...,...,...,...,...,...
9995,10196,The Last Airbender,"The story follows the adventures of Aang, a yo...","Action,Adventure,Fantasy","The story follows the adventures of Aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...,"Action,TV Movie,Science Fiction,Comedy,Adventure",The sharks take bite out of the East Coast whe...
9997,13995,Captain America,"During World War II, a brave, patriotic Americ...","Action,Science Fiction,War","During World War II, a brave, patriotic Americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...,"Adventure,Fantasy,Action,Drama",A man named Farmer sets out to rescue his kidn...
9999,455957,Domino,Seeking justice for his partner’s murder by an...,"Thriller,Action,Crime",Seeking justice for his partner’s murder by an...

In [11]:
new_data  = movies.drop(columns=['overview', 'genre'])

In [12]:
new_data

,id,title,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...
...,...,...,...
9995,10196,The Last Airbender,"The story follows the adventures of Aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...
9997,13995,Captain America,"During World War II, a brave, patriotic Americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...
9999,455957,Domino,Seeking justice for his partner’s murder by an...

In [34]:
'''
max_features: This parameter specifies the maximum number of features (unique words or tokens) to be extracted. In your case, it's set to 10,000, meaning that only the top 10,000 most frequently occurring words in the corpus will be considered as features.

stop_words: This parameter is used to specify a list of words that should be ignored during the tokenization process. In this case, 'english' indicates that a built-in list of English stop words provided by scikit-learn will be used. Stop words are common words such as 'the', 'is', 'and', etc., which are often removed because they typically do not carry significant meaning for text analysis.

When you use CountVectorizer with these parameters, it creates a matrix representation of the text data, where rows correspond to documents and columns correspond to features (words or tokens). Each cell in the matrix contains the count of how many times a particular word appears in the corresponding document. This matrix can then be used as input to machine learning algorithms for tasks such as classification, clustering, or regression.


User
vector=cv.fit_transform(new_data['tags'].values.astype('U')).toarray()
ChatGPT
The code you provided is using the fit_transform() method of the CountVectorizer object (cv) to transform the text data in the 'tags' column of the DataFrame new_data into a matrix of token counts, and then converting it to a NumPy array using toarray() method.

Here's a breakdown of what each part of the code does:

new_data['tags'].values.astype('U'): This extracts the values from the 'tags' column of the DataFrame new_data and converts them to a NumPy array with Unicode data type ('U'). This step is necessary because fit_transform() expects an iterable of string values.

cv.fit_transform(...): This method fits the CountVectorizer object cv to the text data and transforms it into a matrix of token counts. It both learns the vocabulary (i.e., the unique words or tokens) from the text data and transforms the text data into a matrix representation.

.toarray(): This converts the matrix representation returned by fit_transform() into a NumPy array. The matrix representation returned by fit_transform() is typically in a sparse format (i.e., only non-zero elements are stored explicitly), but toarray() converts it into a dense NumPy array format where all elements are stored explicitly.

So, after executing this code, the variable vector will contain a NumPy array representing the matrix of token counts derived from the text data in the 'tags' column of the new_data DataFrame. Each row of the array corresponds to a document (i.e., a tag in this case), and each column corresponds to a unique word or token in the vocabulary learned by the CountVectorizer. The value at position (i, j) in the array represents the count of the j-th word in the i-th document.

User
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vector)
similarity
explain 
ChatGPT
The code snippet you provided is using the cosine_similarity function from scikit-learn's metrics.pairwise module to compute the cosine similarity between the rows (vectors) of the vector array, which likely contains the document-term matrix created using CountVectorizer.

Here's a breakdown of what the code does:

from sklearn.metrics.pairwise import cosine_similarity: This imports the cosine_similarity function from scikit-learn's metrics.pairwise module. Cosine similarity is a metric used to measure the similarity between two vectors in a vector space. It calculates the cosine of the angle between two vectors, which is a measure of how similar or related they are.

similarity = cosine_similarity(vector): This line computes the cosine similarity between all pairs of vectors (rows) in the vector array. Since vector likely represents a document-term matrix where each row corresponds to a document (tag) and each column corresponds to a term (word), cosine_similarity(vector) will compute the cosine similarity between all pairs of documents based on their term frequencies.

similarity: This variable will contain a symmetric matrix where each element (i, j) represents the cosine similarity between the i-th and j-th documents. The diagonal elements (i.e., where i == j) will be 1 because the cosine similarity between a document and itself is 1.

The resulting similarity matrix can be used to identify documents that are similar to each other based on their term frequencies. Higher cosine similarity values indicate greater similarity between documents, while lower values indicate less similarity. This similarity matrix can be useful for various tasks such as clustering similar documents together, identifying related documents, or building recommendation systems.

User
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vector)
similarity 
explain the code 
ChatGPT
Certainly! This code snippet calculates the cosine similarity between vectors using scikit-learn's cosine_similarity function. Here's a detailed explanation:

Importing the necessary module and function:

python
Copy code
from sklearn.metrics.pairwise import cosine_similarity
This line imports the cosine_similarity function from scikit-learn's metrics.pairwise module. This function is specifically designed to compute the cosine similarity between vectors.

Computing cosine similarity:

python
Copy code
similarity = cosine_similarity(vector)
This line calculates the cosine similarity between all pairs of vectors in the vector array. The vector array likely represents a document-term matrix, where each row corresponds to a document (tag) and each column corresponds to a term (word). By default, cosine_similarity calculates the cosine similarity between all pairs of row vectors in the input array. In this case, it calculates the cosine similarity between all pairs of documents based on their term frequencies.

Output:

python
Copy code
similarity
This simply prints or returns the similarity matrix, which contains the cosine similarity values between all pairs of documents. The resulting matrix is symmetric, with each element (i, j) representing the cosine similarity between the i-th and j-th documents.

The cosine similarity is a measure of similarity between two non-zero vectors in an inner product space. It measures the cosine of the angle between the vectors and ranges from -1 to 1, where 1 indicates that the vectors are identical in direction, 0 indicates orthogonality (no similarity), and -1 indicates complete dissimilarity (opposite direction). In the context of document analysis, cosine similarity is commonly used to measure the similarity between documents based on their term frequencies. Higher cosine similarity values imply greater similarity between documents./*

'''

"\nmax_features: This parameter specifies the maximum number of features (unique words or tokens) to be extracted. In your case, it's set to 10,000, meaning that only the top 10,000 most frequently occurring words in the corpus will be considered as features.\n\nstop_words: This parameter is used to specify a list of words that should be ignored during the tokenization process. In this case, 'english' indicates that a built-in list of English stop words provided by scikit-learn will be used. Stop words are common words such as 'the', 'is', 'and', etc., which are often removed because they typically do not carry significant meaning for text analysis.\n\nWhen you use CountVectorizer with these parameters, it creates a matrix representation of the text data, where rows correspond to documents and columns correspond to features (words or tokens). Each cell in the matrix contains the count of how many times a particular word appears in the corresponding document. This matrix can then be used as input to machine learning algorithms for tasks such as classification, clustering, or regression.\n\n\nUser\nvector=cv.fit_transform(new_data['tags'].values.astype('U')).toarray()\nChatGPT\nThe code you provided is using the fit_transform() method of the CountVectorizer object (cv) to transform the text data in the 'tags' column of the DataFrame new_data into a matrix of token counts, and then converting it to a NumPy array using toarray() method.\n\nHere's a breakdown of what each part of the code does:\n\nnew_data['tags'].values.astype('U'): This extracts the values from the 'tags' column of the DataFrame new_data and converts them to a NumPy array with Unicode data type ('U'). This step is necessary because fit_transform() expects an iterable of string values.\n\ncv.fit_transform(...): This method fits the CountVectorizer object cv to the text data and transforms it into a matrix of token counts. It both learns the vocabulary (i.e., the unique words or tokens) from the text data and transforms the text data into a matrix representation.\n\n.toarray(): This converts the matrix representation returned by fit_transform() into a NumPy array. The matrix representation returned by fit_transform() is typically in a sparse format (i.e., only non-zero elements are stored explicitly), but toarray() converts it into a dense NumPy array format where all elements are stored explicitly.\n\nSo, after executing this code, the variable vector will contain a NumPy array representing the matrix of token counts derived from the text data in the 'tags' column of the new_data DataFrame. Each row of the array corresponds to a document (i.e., a tag in this case), and each column corresponds to a unique word or token in the vocabulary learned by the CountVectorizer. The value at position (i, j) in the array represents the count of the j-th word in the i-th document.\n\nUser\nfrom sklearn.metrics.pairwise import cosine_similarity\nsimilarity=cosine_similarity(vector)\nsimilarity\nexplain \nChatGPT\nThe code snippet you provided is using the cosine_similarity function from scikit-learn's metrics.pairwise module to compute the cosine similarity between the rows (vectors) of the vector array, which likely contains the document-term matrix created using CountVectorizer.\n\nHere's a breakdown of what the code does:\n\nfrom sklearn.metrics.pairwise import cosine_similarity: This imports the cosine_similarity function from scikit-learn's metrics.pairwise module. Cosine similarity is a metric used to measure the similarity between two vectors in a vector space. It calculates the cosine of the angle between two vectors, which is a measure of how similar or related they are.\n\nsimilarity = cosine_similarity(vector): This line computes the cosine similarity between all pairs of vectors (rows) in the vector array. Since vector likely represents a document-term matrix where each row corresponds to a document (tag) and each column corresponds to a term (word), cosine_similarity(vector) will compute the cosine similarity between all pairs of documents based on their term frequencies.\n\nsimilarity: This variable will contain a symmetric matrix where each element (i, j) represents the cosine similarity between the i-th and j-th documents. The diagonal elements (i.e., where i == j) will be 1 because the cosine similarity between a document and itself is 1.\n\nThe resulting similarity matrix can be used to identify documents that are similar to each other based on their term frequencies. Higher cosine similarity values indicate greater similarity between documents, while lower values indicate less similarity. This similarity matrix can be useful for various tasks such as clustering similar documents together, identifying related documents, or building recommendation systems.\n\nUser\nfrom sklearn.metrics.pairwise import cosine_similarity\nsimilarity=cosine_similarity(vector)\nsimilarity \nexplain the code \nChatGPT\nCertainly! This code snippet calculates the cosine similarity between vectors using scikit-learn's cosine_similarity function. Here's a detailed explanation:\n\nImporting the necessary module and function:\n\npython\nCopy code\nfrom sklearn.metrics.pairwise import cosine_similarity\nThis line imports the cosine_similarity function from scikit-learn's metrics.pairwise module. This function is specifically designed to compute the cosine similarity between vectors.\n\nComputing cosine similarity:\n\npython\nCopy code\nsimilarity = cosine_similarity(vector)\nThis line calculates the cosine similarity between all pairs of vectors in the vector array. The vector array likely represents a document-term matrix, where each row corresponds to a document (tag) and each column corresponds to a term (word). By default, cosine_similarity calculates the cosine similarity between all pairs of row vectors in the input array. In this case, it calculates the cosine similarity between all pairs of documents based on their term frequencies.\n\nOutput:\n\npython\nCopy code\nsimilarity\nThis simply prints or returns the similarity matrix, which contains the cosine similarity values between all pairs of documents. The resulting matrix is symmetric, with each element (i, j) representing the cosine similarity between the i-th and j-th documents.\n\nThe cosine similarity is a measure of similarity between two non-zero vectors in an inner product space. It measures the cosine of the angle between the vectors and ranges from -1 to 1, where 1 indicates that the vectors are identical in direction, 0 indicates orthogonality (no similarity), and -1 indicates complete dissimilarity (opposite direction). In the context of document analysis, cosine similarity is commonly used to measure the similarity between documents based on their term frequencies. Higher cosine similarity values imply greater similarity between documents./*\n\n"

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

In [14]:
cv=CountVectorizer(max_features=10000, stop_words='english')

In [15]:
cv

CountVectorizer(max_features=10000, stop_words='english')

In [16]:
vector=cv.fit_transform(new_data['tags'].values.astype('U')).toarray()

In [17]:
vector.shape

(10000, 10000)

In [18]:
from sklearn.metrics.pairwise import cosine_similarity

In [19]:
similarity=cosine_similarity(vector)

In [20]:
similarity

array([[1.        , 0.05634362, 0.12888482, ..., 0.07559289, 0.11065667,
        0.06388766],
       [0.05634362, 1.        , 0.07624929, ..., 0.        , 0.03636965,
        0.        ],
       [0.12888482, 0.07624929, 1.        , ..., 0.02273314, 0.06655583,
        0.08645856],
       ...,
       [0.07559289, 0.        , 0.02273314, ..., 1.        , 0.03253   ,
        0.02817181],
       [0.11065667, 0.03636965, 0.06655583, ..., 0.03253   , 1.        ,
        0.0412393 ],
       [0.06388766, 0.        , 0.08645856, ..., 0.02817181, 0.0412393 ,
        1.        ]])

In [21]:
new_data[new_data['title']=="The Godfather"].index[0]

2

In [35]:
distance = sorted(list(enumerate(similarity[2])), reverse=True, key=lambda vector:vector[1])
for i in distance[0:8]:
    print(new_data.iloc[i[0]].title)

The Godfather
The Godfather: Part II
Blood Ties
Joker
Bomb City
Gotti
Felon
Rope

In [23]:
def recommand(movies):
    index=new_data[new_data['title']==movies].index[0]
    distance = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda vector:vector[1])
    for i in distance[0:5]:
        print(new_data.iloc[i[0]].title)

In [33]:
recommand("Set It Up")

Set It Up
Tel chi el telùn
Mystic Pizza
Sex, Love & Therapy
Sierra Burgess Is a Loser